"""new runs

Revision ID: 1c6b7eb1fdf6
Revises: 868032615bfc
Create Date: 2021-02-25 20:51:56.321444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6b7eb1fdf6'
down_revision = '868032615bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_run_see_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_run_see_time')
    # ### end Alembic commands ###
