"""crv unit

Revision ID: 1df12f4e238b
Revises: 4fc885c2e08b
Create Date: 2021-03-24 12:29:00.191904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df12f4e238b'
down_revision = '4fc885c2e08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curve', sa.Column('unit', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curve', 'unit')
    # ### end Alembic commands ###
