"""coords logs core strat

Revision ID: 2dcbfbe021d9
Revises: 055d0e21e9cf
Create Date: 2021-02-01 11:27:25.934476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcbfbe021d9'
down_revision = '055d0e21e9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('data', sa.Binary(), nullable=True),
    sa.Column('top', sa.Float(), nullable=True),
    sa.Column('bottom', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stratigraphy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('lingula_top', sa.Float(), nullable=True),
    sa.Column('lingula_bot', sa.Float(), nullable=True),
    sa.Column('p2ss2_bot', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coords', sa.Column('rkb', sa.Float(), nullable=True))
    op.add_column('coords', sa.Column('well_id', sa.Integer(), nullable=True))
    op.add_column('coords', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('coords', sa.Column('y', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'coords', 'well', ['well_id'], ['id'])
    op.add_column('core', sa.Column('bulk_density', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('interval_end', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('interval_start', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('litho_type', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('oil_saturation_volumetric', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('oil_saturation_weight', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('original_location', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('porosity', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('saturation', sa.Float(), nullable=True))
    op.add_column('core', sa.Column('well_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'core', 'well', ['well_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'core', type_='foreignkey')
    op.drop_column('core', 'well_id')
    op.drop_column('core', 'saturation')
    op.drop_column('core', 'porosity')
    op.drop_column('core', 'original_location')
    op.drop_column('core', 'oil_saturation_weight')
    op.drop_column('core', 'oil_saturation_volumetric')
    op.drop_column('core', 'litho_type')
    op.drop_column('core', 'interval_start')
    op.drop_column('core', 'interval_end')
    op.drop_column('core', 'bulk_density')
    op.drop_constraint(None, 'coords', type_='foreignkey')
    op.drop_column('coords', 'y')
    op.drop_column('coords', 'x')
    op.drop_column('coords', 'well_id')
    op.drop_column('coords', 'rkb')
    op.drop_table('stratigraphy')
    op.drop_table('curve')
    op.drop_table('well')
    # ### end Alembic commands ###
