"""run id to data

Revision ID: 308cd45fd725
Revises: eae98cb13c55
Create Date: 2021-02-08 14:46:51.960421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308cd45fd725'
down_revision = 'eae98cb13c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coords', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coords', 'run', ['run_id'], ['id'])
    op.add_column('curve', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curve', 'run', ['run_id'], ['id'])
    op.add_column('stratigraphy', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stratigraphy', 'run', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stratigraphy', type_='foreignkey')
    op.drop_column('stratigraphy', 'run_id')
    op.drop_constraint(None, 'curve', type_='foreignkey')
    op.drop_column('curve', 'run_id')
    op.drop_constraint(None, 'coords', type_='foreignkey')
    op.drop_column('coords', 'run_id')
    # ### end Alembic commands ###
