"""error files

Revision ID: 314036f158d2
Revises: 4edde9afa746
Create Date: 2021-04-05 09:25:38.246653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '314036f158d2'
down_revision = '4edde9afa746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('SURF_TOP', 'SURF_BOT', 'GRID', 'GRID_FES', name='struct'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dummy_pkey')
    )
    op.drop_table('error_file')
    # ### end Alembic commands ###
