"""struct run

Revision ID: 3680f6fed64a
Revises: 8d30a9e64067
Create Date: 2021-03-19 13:48:40.420033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3680f6fed64a'
down_revision = '8d30a9e64067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('struct_file', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'struct_file', 'run', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'struct_file', type_='foreignkey')
    op.drop_column('struct_file', 'run_id')
    # ### end Alembic commands ###
