"""strat p2ss2

Revision ID: 3f45def6dc36
Revises: 308cd45fd725
Create Date: 2021-02-09 12:25:00.358388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f45def6dc36'
down_revision = '308cd45fd725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stratigraphy', sa.Column('p2ss2_top', sa.Float(), nullable=True))
    op.drop_column('stratigraphy', 'lingula_bot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stratigraphy', sa.Column('lingula_bot', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stratigraphy', 'p2ss2_top')
    # ### end Alembic commands ###
