"""core no res

Revision ID: 413afa6fdbad
Revises: 92183698f0ae
Create Date: 2021-02-19 12:56:56.801301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413afa6fdbad'
down_revision = '92183698f0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core', 'res_filepath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core', sa.Column('res_filepath', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
