"""depth pickle

Revision ID: 4edde9afa746
Revises: da9264441f7f
Create Date: 2021-03-26 13:39:51.472689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edde9afa746'
down_revision = 'da9264441f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('depth', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well', 'depth')
    # ### end Alembic commands ###
