"""depth

Revision ID: 4fc885c2e08b
Revises: b9d0f8342d15
Create Date: 2021-03-24 10:59:30.647704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc885c2e08b'
down_revision = 'b9d0f8342d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('depth', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well', 'depth')
    # ### end Alembic commands ###
