"""well with project_id

Revision ID: 59e32e55e500
Revises: 2dcbfbe021d9
Create Date: 2021-02-04 09:17:17.986701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e32e55e500'
down_revision = '2dcbfbe021d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'well', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'well', type_='foreignkey')
    op.drop_column('well', 'project_id')
    # ### end Alembic commands ###
