"""crv filename

Revision ID: 5e45de1471d3
Revises: 1df12f4e238b
Create Date: 2021-03-24 12:29:47.314970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e45de1471d3'
down_revision = '1df12f4e238b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curve', sa.Column('filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curve', 'filename')
    # ### end Alembic commands ###
