"""core res

Revision ID: 6a077d222220
Revises: e2207400a176
Create Date: 2021-02-19 12:06:30.241336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a077d222220'
down_revision = 'e2207400a176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core', sa.Column('res_filepath', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core', 'res_filepath')
    # ### end Alembic commands ###
