"""well id

Revision ID: 6ad8798dbe34
Revises: 192b6d9b530d
Create Date: 2021-03-12 14:06:04.050165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad8798dbe34'
down_revision = '192b6d9b530d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('well_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_well_name'), 'well', ['name'], unique=False)
    op.create_index(op.f('ix_well_well_id'), 'well', ['well_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_well_well_id'), table_name='well')
    op.drop_index(op.f('ix_well_name'), table_name='well')
    op.drop_column('well', 'well_id')
    # ### end Alembic commands ###
