"""core run

Revision ID: 92183698f0ae
Revises: 6a077d222220
Create Date: 2021-02-19 12:29:41.424994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92183698f0ae'
down_revision = '6a077d222220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'core', 'run', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'core', type_='foreignkey')
    op.drop_column('core', 'run_id')
    # ### end Alembic commands ###
