"""struct type NEW4

Revision ID: 9c2161597a76
Revises: 37481c7a8915
Create Date: 2021-03-21 09:38:43.375822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c2161597a76'
down_revision = '37481c7a8915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('struct_file', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('struct_file', sa.Column('type', postgresql.ENUM('SURF_TOP', 'SURF_BOT', 'GRID', 'GRID_FES', name='struct'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
