"""core res again

Revision ID: b63226062255
Revises: 413afa6fdbad
Create Date: 2021-02-19 12:59:31.395847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63226062255'
down_revision = '413afa6fdbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core', sa.Column('res_filepath', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core', 'res_filepath')
    # ### end Alembic commands ###
