"""struct type NEW5

Revision ID: b9d0f8342d15
Revises: 9c2161597a76
Create Date: 2021-03-21 09:39:19.421119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d0f8342d15'
down_revision = '9c2161597a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('struct_file', sa.Column('type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('struct_file', 'type')
    # ### end Alembic commands ###
