"""reports in run

Revision ID: be3ae7baf82a
Revises: 1c6b7eb1fdf6
Create Date: 2021-03-05 12:42:23.723386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3ae7baf82a'
down_revision = '1c6b7eb1fdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('report_1', sa.String(length=255), nullable=True))
    op.add_column('run', sa.Column('report_2', sa.String(length=255), nullable=True))
    op.add_column('run', sa.Column('report_3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'report_3')
    op.drop_column('run', 'report_2')
    op.drop_column('run', 'report_1')
    # ### end Alembic commands ###
