"""struct del

Revision ID: c9afe6a7c9eb
Revises: b23be10a3e42
Create Date: 2021-03-21 09:28:06.928096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9afe6a7c9eb'
down_revision = 'b23be10a3e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('struct_file', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('struct_file', sa.Column('type', postgresql.ENUM('SURF_TOP', 'SURF_BOT', 'GRID', 'GRID_FES', name='struct'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
