"""strat file 00

Revision ID: d11feb3191e0
Revises: 3680f6fed64a
Create Date: 2021-03-21 09:13:45.367053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11feb3191e0'
down_revision = '3680f6fed64a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('try',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('try')
    # ### end Alembic commands ###
