"""struct files

Revision ID: daa7480286e2
Revises: 3b69b1b7ee74
Create Date: 2021-03-18 09:05:46.661892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa7480286e2'
down_revision = '3b69b1b7ee74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('struct_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('SURF_TOP', 'SURF_BOT', 'GRID', 'GRID_FES', name='struct'), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('struct_file')
    # ### end Alembic commands ###
