"""projects users

Revision ID: e059a0b57115
Revises: 5bd133887d03
Create Date: 2021-01-27 12:23:50.124200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e059a0b57115'
down_revision = '5bd133887d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='projects_users_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='projects_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name='projects_users_pkey')
    )
    # ### end Alembic commands ###
