"""core well_id

Revision ID: e2207400a176
Revises: 3f45def6dc36
Create Date: 2021-02-19 11:14:46.683878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2207400a176'
down_revision = '3f45def6dc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core', sa.Column('well_data_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core', 'well_data_id')
    # ### end Alembic commands ###
